import json

# All stat names found in JSON
json_stats = {
    "'Single Fire' fire rate",
    "1st reveal windup time",
    "2nd reveal windup time",
    "ADS Zoom",
    "Activation animation duration",
    "Activation cooldowns",
    "Activation delay (without Empress)",
    "Activation duration",
    "Activation window upon eligible takedown",
    "Activation windup",
    "Activation windup time",
    "Ammunition",
    "Anchor radius",
    "Angle",
    "Area",
    "Area size",
    "Arena creation duration",
    "Arrival audio cue radius",
    "Audio cue radius",
    "Barrier lengths",
    "Base dash distance",
    "Beacon duration",
    "Blast delay",
    "Blast windup",
    "Blind windup on target acquisition",
    "Bonus movement speed",
    "Buff duration",
    "Buffs",
    "Bullet tagging slow",
    "Buy Phase pickup range",
    "Capture windup",
    "Cast delay",
    "Cast time",
    "Channel time",
    "Cocoon duration",
    "Column area",
    "Concuss duration",
    "Contingency duration",
    "Cylinder radius",
    "Cylinder size",
    "Damage",
    "Damage multipliers",
    "Damage per distance",
    "Dart cooldown",
    "Dart removal channel time",
    "Dash Duration",
    "Dash distance",
    "Dash duration",
    "Deactivation duration",
    "Deactivation time",
    "Debuff",
    "Debuff duration",
    "Decay Stats",
    "Decay duration",
    "Decay rates",
    "Decay stats",
    "Delay between successive segment detonations",
    "Deploy time",
    "Deployment distance",
    "Deployment duration",
    "Deployment time",
    "Detain duration",
    "Detection cone angle",
    "Detection distance",
    "Detection radii",
    "Detection radius",
    "Detonation Ticks/Tick Rate per segment",
    "Detonation radius",
    "Displacement Distance",
    "Distance between Breach and AoE",
    "Distance between Iso and wall on cast",
    "Distance between Waylay and AoE",
    "Distance between walls",
    "Distance required to move away when affected",
    "Downed Duration",
    "Downed Health",
    "Duration",
    "Duration (if stopped)",
    "Duration while applying nearsight",
    "Effective active duration",
    "Effective distance between Harbor and wave",
    "Empowered Duration",
    "Empowered duration",
    "Energy orb duration",
    "Equip time",
    "Expiration warning at 3.7 seconds",
    "Explosion radius",
    "Explosion windup time",
    "Eye duration",
    "Fake decal duration",
    "Fire mode",
    "Fire rate",
    "Flash activation windup time",
    "Flash angle",
    "Flash max duration windup time",
    "Flash windup time",
    "Flight altitude",
    "Flow state duration",
    "Heal-over-time",
    "Healing",
    "Healing duration",
    "Healing pool",
    "Height: 2.5 meters",
    "Hinder duration",
    "Initial distance between agents on Arena spawn",
    "Initial summon time",
    "Initial windup time",
    "Integrity duration",
    "Integrity regeneration rate",
    "Jammed duration",
    "Jump distance",
    "Knockback distance",
    "Length",
    "Lunge distance",
    "Lunge duration",
    "Lunge radius",
    "Max Concuss duration",
    "Max Duration",
    "Max blind duration",
    "Max cast distance",
    "Max cast length",
    "Max cast radius",
    "Max cast radius for cloud's center",
    "Max cast range",
    "Max deploy distance",
    "Max deploy height",
    "Max deploy length",
    "Max detection cone distance",
    "Max detection distance",
    "Max duel duration",
    "Max duration",
    "Max duration allowed for damaging assist to enable ability activation",
    "Max flash duration",
    "Max lifespan",
    "Max projectile duration",
    "Max recall distance",
    "Max targeting distance",
    "Max travel time in air",
    "Max vision radius",
    "Max vision radius while nearsighted",
    "Max wall penetration",
    "Max wall penetration depth",
    "Max windup time",
    "Max wire length",
    "Maximum Overheal",
    "Maximum air time",
    "Maximum bend",
    "Maximum decayed health",
    "Maximum drop",
    "Maximum image duration",
    "Maximum intangibility duration",
    "Maximum pulse travel distance",
    "Maximum radius",
    "Maximum rise",
    "Maximum travel time in air",
    "Minimum charge times and projectile strengths",
    "Movement penalties",
    "Movement speed increase",
    "Nearsight duration",
    "Nearsight vision radius",
    "Nearsighted vision radius",
    "Net removal channel time",
    "Orb velocity",
    "Overheal duration (without Empress)",
    "Overhealing rates",
    "Overloaded Duration",
    "Pickup distance (Buy phase only)",
    "Placement deploy time",
    "Plasma blind duration",
    "Plasma explosion radius on target",
    "Proximity needed to target to nearsight",
    "Proximity radius to remain active",
    "Proximity to target needed to activate blast",
    "Proximity to target needed to explode",
    "Pull duration",
    "Pulse heal",
    "Pulse radius",
    "Pulse radius at path end",
    "Pulse rate",
    "Pulse speed",
    "Pulse velocity",
    "Quick equip time",
    "Radii",
    "Radius",
    "Re-arm time",
    "Re-stealth timer",
    "Reactivation time",
    "Reactivation windup",
    "Recall duration",
    "Recall time",
    "Reequip time",
    "Reload speed increase",
    "Reload time",
    "Resurrection timer",
    "Reveal duration",
    "Reveal stats",
    "Reveal ticks/tick Rate",
    "Revive duration",
    "Round Start windup time",
    "Run speed",
    "Search duration",
    "Search radius",
    "Self-blind duration on arrival",
    "Self-knockback distance",
    "Shield deactivation time",
    "Shield unequip time",
    "Shield width",
    "Shield windup",
    "Size",
    "Slide distance",
    "Slide duration",
    "Slow Duration",
    "Slow amount",
    "Slow duration",
    "Slow potency",
    "Slow radius",
    "Smoke deactivation time",
    "Smoke unequip time",
    "Sonar pulses",
    "Speed",
    "Sphere Velocity",
    "Stabilization duration",
    "Suppress duration",
    "Suppression duration",
    "Targeting delay",
    "Telegraph windup time",
    "Teleport audio cue radius",
    "Teleport duration",
    "Tether Duration",
    "Tether audio cue radius",
    "Tick/Tick rate",
    "Ticks/Tick Rate",
    "Ticks/Tick rate",
    "Time needed to arm",
    "Time required to fully charge",
    "Time taken to fortify",
    "Time taken to fully form",
    "Time until exit on kill",
    "Total 76-79 (152-158 with Vulnerable)",
    "Trail duration",
    "Transportation duration to and from arena",
    "Travel distance",
    "Travel duration",
    "Travel speeds",
    "Triggered Slow duration",
    "Unequip time",
    "Unequip time (out of ammo)",
    "Unequip times (out of ammo)",
    "Unequip/Return time",
    "Uneuqip time",
    "Velocity",
    "Vision cone angle",
    "Vision radius",
    "Vision restoration duration",
    "Vortex radius",
    "Vulnerable duration",
    "Wall Dimensions",
    "Wall Dissolve Duration",
    "Wall Height",
    "Wall dimensions",
    "Wall penetration",
    "Width: 1 meter",
    "Windup",
    "Windup time",
    "Windup time on bounce",
    "Windup time per charge",
    "Windup times",
    "Windup to first pulse",
    "Zone Duration",
    "Zone radius",
    # Meta stats
    "charges",
    "creds",
    "ult_points"
}

# All keys in STAT_NAME_KO from SimulatorClient.tsx
stat_name_ko_keys = {
    "charges",
    "creds",
    "ult_points",
    "Unequip time",
    "Equip time",
    "Windup time",
    "Duration",
    "Deploy time",
    "Windup",
    "Concuss duration",
    "Slow duration",
    "Teleport duration",
    "Nearsight duration",
    "Deactivation time",
    "Buff duration",
    "Vulnerable duration",
    "Revive duration",
    "Max blind duration",
    "Max flash duration",
    "Max duration",
    "Search duration",
    "Debuff duration",
    "Channel time",
    "Cast time",
    "Deployment time",
    "Reequip time",
    "Quick equip time",
    "Recall duration",
    "Recall time",
    "Reactivation time",
    "Activation windup",
    "Activation windup time",
    "Detain duration",
    "Suppression duration",
    "Suppress duration",
    "Resurrection timer",
    "Initial windup time",
    "Initial summon time",
    "Maximum air time",
    "Empowered Duration",
    "Empowered duration",
    "Dash Duration",
    "Dash duration",
    "Healing duration",
    "Activation duration",
    "Cocoon duration",
    "Eye duration",
    "Trail duration",
    "Tether Duration",
    "Zone Duration",
    "Wall Dissolve Duration",
    "Slide duration",
    "Stabilization duration",
    "Overloaded Duration",
    "Downed Duration",
    "Round Start windup time",
    "Activation animation duration",
    "Windup times",
    "Windup time on bounce",
    "Max windup time",
    "Windup time per charge",
    "Flash windup time",
    "Flash activation windup time",
    "Flash max duration windup time",
    "Telegraph windup time",
    "Blind windup on target acquisition",
    "Explosion windup time",
    "Activation delay (without Empress)",
    "Activation window upon eligible takedown",
    "Overheal duration (without Empress)",
    "Shield windup",
    "Shield deactivation time",
    "Shield unequip time",
    "Smoke deactivation time",
    "Smoke unequip time",
    "Re-arm time",
    "Re-stealth timer",
    "Reload time",
    "Dart cooldown",
    "Dart removal channel time",
    "Net removal channel time",
    "Placement deploy time",
    "Beacon duration",
    "1st reveal windup time",
    "2nd reveal windup time",
    "Triggered Slow duration",
    "Delay between successive segment detonations",
    "Time taken to fully form",
    "Time required to fully charge",
    "Time taken to fortify",
    "Time needed to arm",
    "Fake decal duration",
    "Maximum image duration",
    "Unequip time (out of ammo)",
    "Unequip times (out of ammo)",
    "Unequip/Return time",
    "Uneuqip time",
    "Self-blind duration on arrival",
    "Duration while applying nearsight",
    "Duration (if stopped)",
    "Contingency duration",
    "Time until exit on kill",
    "Transportation duration to and from arena",
    "Arena creation duration",
    "Max duel duration",
    "Plasma blind duration",
    "Flow state duration",
    "Energy orb duration",
    "Vision restoration duration",
    "Activation cooldowns",
    "Max duration allowed for damaging assist to enable ability activation",
    "Radius",
    "Radii",
    "Area size",
    "Max deploy distance",
    "Max deploy length",
    "Max deploy height",
    "Detection radius",
    "Detection distance",
    "Detection radii",
    "Detection cone angle",
    "Max detection cone distance",
    "Max detection distance",
    "Max cast distance",
    "Max cast range",
    "Max cast length",
    "Max cast radius",
    "Max cast radius for cloud's center",
    "Travel distance",
    "Base dash distance",
    "Dash distance",
    "Slide distance",
    "Lunge distance",
    "Lunge radius",
    "Jump distance",
    "Displacement Distance",
    "Knockback distance",
    "Self-knockback distance",
    "Proximity radius to remain active",
    "Proximity to target needed to explode",
    "Proximity to target needed to activate blast",
    "Proximity needed to target to nearsight",
    "Distance between Iso and wall on cast",
    "Distance between Breach and AoE",
    "Distance between Waylay and AoE",
    "Distance between walls",
    "Distance required to move away when affected",
    "Audio cue radius",
    "Arrival audio cue radius",
    "Teleport audio cue radius",
    "Tether audio cue radius",
    "Anchor radius",
    "Search radius",
    "Slow radius",
    "Zone radius",
    "Pulse radius",
    "Pulse radius at path end",
    "Maximum pulse travel distance",
    "Explosion radius",
    "Detonation radius",
    "Plasma explosion radius on target",
    "Max wall penetration",
    "Max wall penetration depth",
    "Max wire length",
    "Max recall distance",
    "Max projectile duration",
    "Max lifespan",
    "Max targeting distance",
    "Max vision radius",
    "Max vision radius while nearsighted",
    "Nearsight vision radius",
    "Nearsighted vision radius",
    "Vision radius",
    "Vision cone angle",
    "Maximum radius",
    "Cylinder size",
    "Cylinder radius",
    "Column area",
    "Area",
    "Size",
    "Length",
    "Barrier lengths",
    "Maximum bend",
    "Wall Height",
    "Wall Dimensions",
    "Effective distance between Harbor and wave",
    "Maximum rise",
    "Maximum drop",
    "Initial distance between agents on Arena spawn",
    "Buy Phase pickup range",
    "Deployment distance",
    "Deployment duration",
    "Effective active duration",
    "Pickup distance (Buy phase only)",
    "Vortex radius",
    "Flight altitude",
    "Damage",
    "Damage per distance",
    "Healing",
    "Healing pool",
    "Heal-over-time",
    "Pulse heal",
    "Maximum Overheal",
    "Maximum decayed health",
    "Decay duration",
    "Decay stats",
    "Decay Stats",
    "Downed Health",
    "Debuff",
    "Integrity duration",
    "Integrity regeneration rate",
    "Velocity",
    "Speed",
    "Orb velocity",
    "Sphere Velocity",
    "Pulse velocity",
    "Pulse speed",
    "Run speed",
    "Movement speed increase",
    "Bonus movement speed",
    "Travel speeds",
    "Travel duration",
    "Bullet tagging slow",
    "Slow potency",
    "Slow Duration",
    "Slow amount",
    "Lunge duration",
    "Fire rate",
    "'Single Fire' fire rate",
    "Ammunition",
    "Angle",
    "Flash angle",
    "Ticks/Tick Rate",
    "Ticks/Tick rate",
    "Tick/Tick rate",
    "Detonation Ticks/Tick Rate per segment",
    "Buffs",
    "Jammed duration",
    "Hinder duration",
    "Shield width",
    "Reveal stats",
    "Reveal duration",
    "Reveal ticks/tick Rate",
    "Sonar pulses",
    "Pulse rate",
    "Windup to first pulse",
    "Reload speed increase",
    "Maximum intangibility duration",
    "Targeting delay",
    "Damage multipliers",
    "Capture windup",
    "Reactivation windup",
}

# Find missing stats
missing = json_stats - stat_name_ko_keys

print("=" * 70)
print(f"MISSING KOREAN TRANSLATIONS: {len(missing)} stats not in STAT_NAME_KO")
print("=" * 70)
for stat in sorted(missing):
    print(f"  {stat}")
